name: 'Deploy to Azure App Service Using Azure CLI'

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  AZURE_WEBAPP_NAME: PSDeployDemo

jobs:
  build:
    env:
      BUILD_CONFIG: Release
      DOT_NET_VERSION: 5.0.x
      
    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ env.DOT_NET_VERSION }}'      
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration '${{ env.BUILD_CONFIG }}'
      
    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
             
    - name: Zip publish files
      run: (cd myapp && zip -r ../deployfile.zip .)
             
    - uses: actions/upload-artifact@v2
      with:
        name: zippedpackage
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/deployfile.zip         
             
    - name: "Login and deploy to App Service"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.24.2
        inlineScript: |
          az login --identity
          az webapp deploy --resource-group PSDeploy --name ${{ env.AZURE_WEBAPP_NAME }} --type zip --src-path ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/deployfile.zip